version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barohanpo-be
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
