name: Deploy Swagger Docs to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*.js'
      - 'generate-swagger.js'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Swagger docs
        run: npm run generate-swagger
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          single-commit: true
