name: Deploy Swagger Docs to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*.js'
      - 'generate-swagger.js'
      - 'package.json'
      - '.github/workflows/deploy-docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # 권한 설정 추가
    permissions:
      contents: write
      pages: write
      id-token: write
    
    # 배포 환경 설정
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Swagger docs
        run: |
          echo "Current directory: $(pwd)"
          npm run generate-swagger
          echo "Generated files in docs/:"
          ls -la docs/
          echo "File content of swagger.json:"
          cat docs/swagger.json | head -n 20
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          single-commit: true
          force: true
          silent: false
          verbose: true
      
      - name: Show deployment status
        run: |
          echo "Deployment status: ${{ steps.deployment.outcome }}"
          echo "Page URL: ${{ steps.deployment.outputs.page_url }}"
